/*
 * People Management API - BRA
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Iatec.Adems.PeopleManagement.Client.Model
{
    /// <summary>
    /// NaturalPersonHealthPlanLiteModel
    /// </summary>
    [DataContract]
    public partial class NaturalPersonHealthPlanLiteModel : IEquatable<NaturalPersonHealthPlanLiteModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NaturalPersonHealthPlanLiteModel" /> class.
        /// </summary>
        /// <param name="Id">Id.</param>
        /// <param name="ExpirationDate">ExpirationDate.</param>
        /// <param name="HealthPlan">HealthPlan.</param>
        /// <param name="MedicalId">MedicalId.</param>
        /// <param name="NaturalPersonId">NaturalPersonId.</param>
        public NaturalPersonHealthPlanLiteModel(Guid Id = default(Guid), DateTime ExpirationDate = default(DateTime), HealthPlanModel HealthPlan = default(HealthPlanModel), 
            string MedicalId = default(string), Guid NaturalPersonId = default(Guid))
        {
            this.Id = Id;
            this.ExpirationDate = ExpirationDate;
            this.HealthPlan = HealthPlan;
            this.MedicalId = MedicalId;
            this.NaturalPersonId = NaturalPersonId;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets ExpirationDate
        /// </summary>
        [DataMember(Name = "expirationDate", EmitDefaultValue = false)]
        public DateTime ExpirationDate { get; set; }

        /// <summary>
        /// Gets or Sets HealthPlan
        /// </summary>
        [DataMember(Name = "healthPlan", EmitDefaultValue = false)]
        public HealthPlanModel HealthPlan { get; set; }

        /// <summary>
        /// Gets or Sets MedicalId
        /// </summary>
        [DataMember(Name = "medicalId", EmitDefaultValue = false)]
        public string MedicalId { get; set; }

        /// <summary>
        /// Gets or Sets NaturalPersonId
        /// </summary>
        [DataMember(Name = "naturalPersonId", EmitDefaultValue = false)]
        public Guid NaturalPersonId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NaturalPersonHealthPlanLiteModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ExpirationDate: ").Append(ExpirationDate).Append("\n");
            sb.Append("  HealthPlan: ").Append(HealthPlan).Append("\n");
            sb.Append("  MedicalId: ").Append(MedicalId).Append("\n");
            sb.Append("  NaturalPersonId: ").Append(NaturalPersonId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NaturalPersonHealthPlanLiteModel);
        }

        /// <summary>
        /// Returns true if NaturalPersonHealthPlanLiteModel instances are equal
        /// </summary>
        /// <param name="input">Instance of NaturalPersonHealthPlanLiteModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NaturalPersonHealthPlanLiteModel input)
        {
            if (input == null)
                return false;

            return
                (
                    this.Id == input.Id ||
                    (this.Id != default(Guid) &&
                    this.Id.Equals(input.Id))
                ) &&
                (
                    this.ExpirationDate == input.ExpirationDate ||
                    (this.ExpirationDate != null &&
                    this.ExpirationDate.Equals(input.ExpirationDate))
                ) &&
                (
                    this.HealthPlan == input.HealthPlan ||
                    (this.HealthPlan != null &&
                    this.HealthPlan.Equals(input.HealthPlan))
                ) &&
                (
                    this.MedicalId == input.MedicalId ||
                    (this.MedicalId != null &&
                    this.MedicalId.Equals(input.MedicalId))
                ) &&
                (
                    this.NaturalPersonId == input.NaturalPersonId ||
                    (this.NaturalPersonId != default(Guid) &&
                    this.NaturalPersonId.Equals(input.NaturalPersonId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != default(Guid))
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.ExpirationDate != null)
                    hashCode = hashCode * 59 + this.ExpirationDate.GetHashCode();
                if (this.HealthPlan != null)
                    hashCode = hashCode * 59 + this.HealthPlan.GetHashCode();
                if (this.MedicalId != null)
                    hashCode = hashCode * 59 + this.MedicalId.GetHashCode();
                if (this.NaturalPersonId != default(Guid))
                    hashCode = hashCode * 59 + this.NaturalPersonId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}